In [2]:
import pandas as pd
import plotly.express as px 
import plotly.graph_objects as go
import numpy as np

In [3]:
raw_data = pd.read_excel('get_around_delay_analysis.xlsx')
raw_data.shape

(21310, 7)

In [4]:
raw_data.describe(include='all')

,rental_id,car_id,checkin_type,state,delay_at_checkout_in_minutes,previous_ended_rental_id,time_delta_with_previous_rental_in_minutes
count,21310.000000,21310.000000,21310,21310,16346.000000,1841.000000,1841.000000
unique,NaN,NaN,2,2,NaN,NaN,NaN
top,NaN,NaN,mobile,ended,NaN,NaN,NaN
freq,NaN,NaN,17003,18045,NaN,NaN,NaN
mean,549712.880338,350030.603426,NaN,NaN,59.701517,550127.411733,279.288430
std,13863.446964,58206.249765,NaN,NaN,1002.561635,13184.023111,254.594486
min,504806.000000,159250.000000,NaN,NaN,-22433.000000,505628.000000,0.000000
25%,540613.250000,317639.000000,NaN,NaN,-36.000000,540896.000000,60.000000
50%,550350.000000,368717.000000,NaN,NaN,9.000000,550567.000000,180.000000
75%,560468.500000,394928.000000,NaN,NaN,67.000000,560823.000000,540.000000
max,576401.000000,417675.000000,NaN,NaN,71084.000000,575053.000000,720.000000

In [5]:
raw_data.head()

,rental_id,car_id,checkin_type,state,delay_at_checkout_in_minutes,previous_ended_rental_id,time_delta_with_previous_rental_in_minutes
0,505000,363965,mobile,canceled,NaN,NaN,NaN
1,507750,269550,mobile,ended,-81.0,NaN,NaN
2,508131,359049,connect,ended,70.0,NaN,NaN
3,508865,299063,connect,canceled,NaN,NaN,NaN
4,511440,313932,mobile,ended,NaN,NaN,NaN

In [6]:
temp_data = raw_data[raw_data['state'] == 'ended'] #not the canceled ones
temp_data = temp_data.merge(temp_data[['rental_id', 'delay_at_checkout_in_minutes', 'checkin_type']], 
                            how='left', left_on='previous_ended_rental_id', right_on='rental_id',
                            suffixes=['','_previous']) #add the Chackout delay of the previous rental
temp_data = temp_data.drop(['rental_id_previous', 'state'], axis=1) #drop duplicate
temp_data['type_issame'] = temp_data['checkin_type'] == temp_data['checkin_type_previous'] 
data = temp_data[temp_data['delay_at_checkout_in_minutes_previous'].notna()]
data['overlap'] = data['delay_at_checkout_in_minutes_previous'] - data['time_delta_with_previous_rental_in_minutes'] #if overlap negative, then there is enough delta
data['previous_late'] = data['delay_at_checkout_in_minutes_previous']>0
data['impacted'] = data['overlap'] > 0
data.head()

C:\Users\dubos\AppData\Local\Temp\ipykernel_3868\2928866813.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['overlap'] = data['delay_at_checkout_in_minutes_previous'] - data['time_delta_with_previous_rental_in_minutes'] #if overlap negative, then there is enough delta
C:\Users\dubos\AppData\Local\Temp\ipykernel_3868\2928866813.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['previous_late'] = data['delay_at_checkout_in_minutes_previous']>0
C:\Users\dubos\AppData\Local\Temp\ipykernel_3868\2928866813.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['impacted'] = data['overlap'] > 0

,rental_id,car_id,checkin_type,delay_at_checkout_in_minutes,previous_ended_rental_id,time_delta_with_previous_rental_in_minutes,delay_at_checkout_in_minutes_previous,checkin_type_previous,type_issame,overlap,previous_late,impacted
4,511639,370585,connect,-15.0,563782.0,570.0,136.0,connect,True,-434.0,True,False
13,519491,312389,mobile,58.0,545639.0,420.0,140.0,mobile,True,-280.0,True,False
24,525044,349751,mobile,NaN,510607.0,60.0,-113.0,mobile,True,-173.0,False,False
30,528808,181625,connect,-76.0,557404.0,330.0,-352.0,connect,True,-682.0,False,False
50,533670,320824,connect,-6.0,556563.0,630.0,23.0,connect,True,-607.0,True,False

In [7]:
data.describe(include='all')

,rental_id,car_id,checkin_type,delay_at_checkout_in_minutes,previous_ended_rental_id,time_delta_with_previous_rental_in_minutes,delay_at_checkout_in_minutes_previous,checkin_type_previous,type_issame,overlap,previous_late,impacted
count,1523.000000,1523.000000,1523,1476.000000,1523.000000,1523.000000,1523.000000,1523,1523,1523.000000,1523,1523
unique,NaN,NaN,2,NaN,NaN,NaN,NaN,2,2,NaN,2,2
top,NaN,NaN,mobile,NaN,NaN,NaN,NaN,mobile,True,NaN,True,False
freq,NaN,NaN,853,NaN,NaN,NaN,NaN,859,1509,NaN,767,1342
mean,552227.014445,351745.271832,NaN,28.134146,549869.814839,273.683519,-22.427446,NaN,NaN,-296.110965,NaN,NaN
std,12956.650124,54244.297467,NaN,429.744537,13383.286259,254.809242,443.314397,NaN,NaN,505.846041,NaN,NaN
min,505560.000000,159533.000000,NaN,-1707.000000,505628.000000,0.000000,-4624.000000,NaN,NaN,-4684.000000,NaN,NaN
25%,543567.500000,323987.000000,NaN,-47.000000,540738.000000,60.000000,-52.500000,NaN,NaN,-572.500000,NaN,NaN
50%,552310.000000,368432.000000,NaN,4.000000,550317.000000,180.000000,1.000000,NaN,NaN,-199.000000,NaN,NaN
75%,562481.000000,391449.000000,NaN,54.000000,560749.500000,540.000000,41.000000,NaN,NaN,-47.000000,NaN,NaN
max,576292.000000,415953.000000,NaN,9787.000000,575053.000000,720.000000,12968.000000,NaN,NaN,12548.000000,NaN,NaN

In [8]:
data.to_csv('data_clean.csv')

In [9]:
data_late = data.groupby('time_delta_with_previous_rental_in_minutes').agg({'previous_late': ['count', 'sum', 'mean'], 'impacted' : ['sum', 'mean']})
                                                                           
# df.groupby('A').agg({'B': ['min', 'max'], 'C': 'sum'})
data_late['previous_late', 'countcumsum'] = data_late['previous_late', 'count'].cumsum()
data_late['previous_late', 'cumsum'] = data_late['previous_late', 'sum'].cumsum()
data_late['impacted', 'cumsum'] = data_late['impacted', 'sum'].cumsum()
data_late['impacted_by_lateness'] = data_late['impacted', 'mean']/ data_late['previous_late', 'mean']

data_late

                                           previous_late                \
                                                   count sum      mean
time_delta_with_previous_rental_in_minutes
0.0                                                  232  99  0.426724
30.0                                                 112  57  0.508929
60.0                                                 148  64  0.432432
90.0                                                  73  46  0.630137
120.0                                                122  72  0.590164
150.0                                                 55  29  0.527273
180.0                                                 71  38  0.535211
210.0                                                 34  18  0.529412
240.0                                                 56  28  0.500000
270.0                                                 32  22  0.687500
300.0                                                 32  21  0.656250
330.0                                                 21   7  0.333333
360.0                                                 34  26  0.764706
390.0                                                 11  10  0.909091
420.0                                                 29  17  0.586207
450.0                                                 16   9  0.562500
480.0                                                 31  14  0.451613
510.0                                                 28  12  0.428571
540.0                                                 32  19  0.593750
570.0                                                 35  16  0.457143
600.0                                                 54  25  0.462963
630.0                                                 42  23  0.547619
660.0                                                 61  23  0.377049
690.0                                                 49  23  0.469388
720.0                                                113  49  0.433628

                                           impacted           previous_late  \
                                                sum      mean   countcumsum
time_delta_with_previous_rental_in_minutes
0.0                                              99  0.426724           232
30.0                                             28  0.250000           344
60.0                                             21  0.141892           492
90.0                                              7  0.095890           565
120.0                                            10  0.081967           687
150.0                                             2  0.036364           742
180.0                                             3  0.042254           813
210.0                                             1  0.029412           847
240.0                                             3  0.053571           903
270.0                                             0  0.000000           935
300.0                                             1  0.031250           967
330.0                                             0  0.000000           988
360.0                                             0  0.000000          1022
390.0                                             0  0.000000          1033
420.0                                             1  0.034483          1062
450.0                                             1  0.062500          1078
480.0                                             0  0.000000          1109
510.0                                             1  0.035714          1137
540.0                                             1  0.031250          1169
570.0                                             1  0.028571          1204
600.0                                             0  0.000000          1258
630.0                                             0  0.000000          1300
660.0                                             0  0.000000          1361
690.0                                             0  0.000000          1410
720.0                                             1  0.008850          1523

                                                  impacted  \
                                           cumsum   cumsum
time_delta_with_previous_rental_in_minutes
0.0                                            99       99
30.0                                          156      127
60.0                                          220      148
90.0                                          266      155
120.0                                         338      165
150.0                                         367      167
180.0                                         405      170
210.0                                         423      171
240.0                                         451      174
270.0                                         473      174
300.0                                         494      175
330.0                                         501      175
360.0                                         527      175
390.0                                         537      175
420.0                                         554      176
450.0                                         563      177
480.0                                         577      177
510.0                                         589      178
540.0                                         608      179
570.0                                         624      180
600.0                                         649      180
630.0                                         672      180
660.0                                         695      180
690.0                                         718      180
720.0                                         767      181

                                           impacted_by_lateness

time_delta_with_previous_rental_in_minutes
0.0                                                    1.000000
30.0                                                   0.491228
60.0                                                   0.328125
90.0                                                   0.152174
120.0                                                  0.138889
150.0                                                  0.068966
180.0                                                  0.078947
210.0                                                  0.055556
240.0                                                  0.107143
270.0                                                  0.000000
300.0                                                  0.047619
330.0                                                  0.000000
360.0                                                  0.000000
390.0                                                  0.000000
420.0                                                  0.058824
450.0                                                  0.111111
480.0                                                  0.000000
510.0                                                  0.083333
540.0                                                  0.052632
570.0                                                  0.062500
600.0                                                  0.000000
630.0                                                  0.000000
660.0                                                  0.000000
690.0                                                  0.000000
720.0                                                  0.020408

In [10]:
# px.scatter(data)

In [11]:
dataset = pd.read_csv("get_around_pricing_project.csv", index_col=0)
dataset.head()

,model_key,mileage,engine_power,fuel,paint_color,car_type,private_parking_available,has_gps,has_air_conditioning,automatic_car,has_getaround_connect,has_speed_regulator,winter_tires,rental_price_per_day
0,Citroën,140411,100,diesel,black,convertible,True,True,False,False,True,True,True,106
1,Citroën,13929,317,petrol,grey,convertible,True,True,False,False,False,True,True,264
2,Citroën,183297,120,diesel,white,convertible,False,False,False,False,True,False,True,101
3,Citroën,128035,135,diesel,red,convertible,True,True,False,False,True,True,True,158
4,Citroën,97097,160,diesel,silver,convertible,True,True,False,False,False,True,True,183

In [12]:
dataset.describe(include='all')

,model_key,mileage,engine_power,fuel,paint_color,car_type,private_parking_available,has_gps,has_air_conditioning,automatic_car,has_getaround_connect,has_speed_regulator,winter_tires,rental_price_per_day
count,4843,4.843000e+03,4843.00000,4843,4843,4843,4843,4843,4843,4843,4843,4843,4843,4843.000000
unique,28,NaN,NaN,4,10,8,2,2,2,2,2,2,2,NaN
top,Citroën,NaN,NaN,diesel,black,estate,True,True,False,False,False,False,True,NaN
freq,969,NaN,NaN,4641,1633,1606,2662,3839,3865,3881,2613,3674,4514,NaN
mean,NaN,1.409628e+05,128.98823,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,121.214536
std,NaN,6.019674e+04,38.99336,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,33.568268
min,NaN,-6.400000e+01,0.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.000000
25%,NaN,1.029135e+05,100.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,104.000000
50%,NaN,1.410800e+05,120.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,119.000000
75%,NaN,1.751955e+05,135.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,136.000000
max,NaN,1.000376e+06,423.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,422.000000

In [13]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4843 entries, 0 to 4842
Data columns (total 14 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   model_key                  4843 non-null   object
 1   mileage                    4843 non-null   int64
 2   engine_power               4843 non-null   int64
 3   fuel                       4843 non-null   object
 4   paint_color                4843 non-null   object
 5   car_type                   4843 non-null   object
 6   private_parking_available  4843 non-null   bool
 7   has_gps                    4843 non-null   bool
 8   has_air_conditioning       4843 non-null   bool
 9   automatic_car              4843 non-null   bool
 10  has_getaround_connect      4843 non-null   bool
 11  has_speed_regulator        4843 non-null   bool
 12  winter_tires               4843 non-null   bool
 13  rental_price_per_day       4843 non-null   int64
dtypes: bool(7), int64(3), object(4)
memory usage: 335.8+ KB

In [14]:
obj_col = dataset.select_dtypes(include="object").columns
obj_col
for col in obj_col:
    value_set = list(set(dataset[col]))
    trad_dic = {}
    for i in range(len(value_set)):
        trad_dic[value_set[i]] = i

    dataset[col]  = dataset[col].map(trad_dic)

print(dataset)

      model_key  mileage  engine_power  fuel  paint_color  car_type  \
0            24   140411           100     0            4         1
1            24    13929           317     1            5         1
2            24   183297           120     0            3         1
3            24   128035           135     0            7         1
4            24    97097           160     0            0         1
...         ...      ...           ...   ...          ...       ...
4838         21    39743           110     0            4         3
4839         21    49832           100     0            5         3
4840         21    19633           110     0            5         3
4841         21    27920           110     0            2         3
4842          1   195840           160     0            5         3

      private_parking_available  has_gps  has_air_conditioning  automatic_car  \
0                          True     True                 False          False
1                          True     True                 False          False
2                         False    False                 False          False
3                          True     True                 False          False
4                          True     True                 False          False
...                         ...      ...                   ...            ...
4838                      False     True                 False          False
4839                      False     True                 False          False
4840                      False     True                 False          False
4841                       True     True                 False          False
4842                       True     True                 False          False

      has_getaround_connect  has_speed_regulator  winter_tires  \
0                      True                 True          True
1                     False                 True          True
2                      True                False          True
3                      True                 True          True
4                     False                 True          True
...                     ...                  ...           ...
4838                  False                False          True
4839                  False                False          True
4840                  False                False          True
4841                  False                False          True
4842                   True                False          True

      rental_price_per_day
0                      106
1                      264
2                      101
3                      158
4                      183
...                    ...
4838                   121
4839                   132
4840                   130
4841                   151
4842                   124

[4843 rows x 14 columns]

In [15]:
# Source - https://stackoverflow.com/a/48271124
# Posted by MaxU - stand with Ukraine, modified by community. See post 'Timeline' for change history
# Retrieved 2026-02-10, License - CC BY-SA 3.0

dataset.loc[:, dataset.dtypes.eq('bool')] = dataset.loc[:, dataset.dtypes.eq('bool')].astype(np.int64)
dataset

C:\Users\dubos\AppData\Local\Temp\ipykernel_3868\1767244680.py:5: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[1 1 0 ... 0 1 1]' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.
  dataset.loc[:, dataset.dtypes.eq('bool')] = dataset.loc[:, dataset.dtypes.eq('bool')].astype(np.int64)
C:\Users\dubos\AppData\Local\Temp\ipykernel_3868\1767244680.py:5: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[1 1 0 ... 1 1 1]' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.
  dataset.loc[:, dataset.dtypes.eq('bool')] = dataset.loc[:, dataset.dtypes.eq('bool')].astype(np.int64)
C:\Users\dubos\AppData\Local\Temp\ipykernel_3868\1767244680.py:5: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0 0 0 ... 0 0 0]' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.
  dataset.loc[:, dataset.dtypes.eq('bool')] = dataset.loc[:, dataset.dtypes.eq('bool')].astype(np.int64)
C:\Users\dubos\AppData\Local\Temp\ipykernel_3868\1767244680.py:5: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0 0 0 ... 0 0 0]' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.
  dataset.loc[:, dataset.dtypes.eq('bool')] = dataset.loc[:, dataset.dtypes.eq('bool')].astype(np.int64)
C:\Users\dubos\AppData\Local\Temp\ipykernel_3868\1767244680.py:5: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[1 0 1 ... 0 0 1]' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.
  dataset.loc[:, dataset.dtypes.eq('bool')] = dataset.loc[:, dataset.dtypes.eq('bool')].astype(np.int64)
C:\Users\dubos\AppData\Local\Temp\ipykernel_3868\1767244680.py:5: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[1 1 0 ... 0 0 0]' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.
  dataset.loc[:, dataset.dtypes.eq('bool')] = dataset.loc[:, dataset.dtypes.eq('bool')].astype(np.int64)
C:\Users\dubos\AppData\Local\Temp\ipykernel_3868\1767244680.py:5: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[1 1 1 ... 1 1 1]' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.
  dataset.loc[:, dataset.dtypes.eq('bool')] = dataset.loc[:, dataset.dtypes.eq('bool')].astype(np.int64)

,model_key,mileage,engine_power,fuel,paint_color,car_type,private_parking_available,has_gps,has_air_conditioning,automatic_car,has_getaround_connect,has_speed_regulator,winter_tires,rental_price_per_day
0,24,140411,100,0,4,1,1,1,0,0,1,1,1,106
1,24,13929,317,1,5,1,1,1,0,0,0,1,1,264
2,24,183297,120,0,3,1,0,0,0,0,1,0,1,101
3,24,128035,135,0,7,1,1,1,0,0,1,1,1,158
4,24,97097,160,0,0,1,1,1,0,0,0,1,1,183
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4838,21,39743,110,0,4,3,0,1,0,0,0,0,1,121
4839,21,49832,100,0,5,3,0,1,0,0,0,0,1,132
4840,21,19633,110,0,5,3,0,1,0,0,0,0,1,130
4841,21,27920,110,0,2,3,1,1,0,0,0,0,1,151
4842,1,195840,160,0,5,3,1,1,0,0,1,0,1,124

In [16]:
bool_col = dataset.select_dtypes(include="bool").columns
bool_col
for col in bool_col:
    value_set = list(set(dataset[col]))
    trad_dic = {}
    for i in range(len(value_set)):
        trad_dic[value_set[i]] = i

    dataset[col]  = dataset[col].map(trad_dic)

print(dataset)

      model_key  mileage  engine_power  fuel  paint_color  car_type  \
0            24   140411           100     0            4         1
1            24    13929           317     1            5         1
2            24   183297           120     0            3         1
3            24   128035           135     0            7         1
4            24    97097           160     0            0         1
...         ...      ...           ...   ...          ...       ...
4838         21    39743           110     0            4         3
4839         21    49832           100     0            5         3
4840         21    19633           110     0            5         3
4841         21    27920           110     0            2         3
4842          1   195840           160     0            5         3

      private_parking_available  has_gps  has_air_conditioning  automatic_car  \
0                             1        1                     0              0
1                             1        1                     0              0
2                             0        0                     0              0
3                             1        1                     0              0
4                             1        1                     0              0
...                         ...      ...                   ...            ...
4838                          0        1                     0              0
4839                          0        1                     0              0
4840                          0        1                     0              0
4841                          1        1                     0              0
4842                          1        1                     0              0

      has_getaround_connect  has_speed_regulator  winter_tires  \
0                         1                    1             1
1                         0                    1             1
2                         1                    0             1
3                         1                    1             1
4                         0                    1             1
...                     ...                  ...           ...
4838                      0                    0             1
4839                      0                    0             1
4840                      0                    0             1
4841                      0                    0             1
4842                      1                    0             1

      rental_price_per_day
0                      106
1                      264
2                      101
3                      158
4                      183
...                    ...
4838                   121
4839                   132
4840                   130
4841                   151
4842                   124

[4843 rows x 14 columns]

In [17]:
brands = list(set(dataset["model_key"]))
dic_brand = {}
for i in range(len(brands)):
    dic_brand[brands[i]] = i
    

dic_brand

{0: 0,
 1: 1,
 2: 2,
 3: 3,
 4: 4,
 5: 5,
 6: 6,
 7: 7,
 8: 8,
 9: 9,
 10: 10,
 11: 11,
 12: 12,
 13: 13,
 14: 14,
 15: 15,
 16: 16,
 17: 17,
 18: 18,
 19: 19,
 20: 20,
 21: 21,
 22: 22,
 23: 23,
 24: 24,
 25: 25,
 26: 26,
 27: 27}

In [18]:
price_car = {
    "Alfa Romeo":'',
    "Audi":44777,
    "BMW":50259,
    "Citroën":22343,
    "Ferrari":'',
    "Fiat":17464,
    "Ford":27032,
    "Honda":''
}

In [19]:
go.Layout?

Init signature:
go.Layout(
    arg=None,
    activeselection=None,
    activeshape=None,
    annotations=None,
    annotationdefaults=None,
    autosize=None,
    autotypenumbers=None,
    barcornerradius=None,
    bargap=None,
    bargroupgap=None,
    barmode=None,
    barnorm=None,
    boxgap=None,
    boxgroupgap=None,
    boxmode=None,
    calendar=None,
    clickmode=None,
    coloraxis=None,
    colorscale=None,
    colorway=None,
    computed=None,
    datarevision=None,
    dragmode=None,
    editrevision=None,
    extendfunnelareacolors=None,
    extendiciclecolors=None,
    extendpiecolors=None,
    extendsunburstcolors=None,
    extendtreemapcolors=None,
    font=None,
    funnelareacolorway=None,
    funnelgap=None,
    funnelgroupgap=None,
    funnelmode=None,
    geo=None,
    grid=None,
    height=None,
    hiddenlabels=None,
    hiddenlabelssrc=None,
    hidesources=None,
    hoverdistance=None,
    hoverlabel=None,
    hovermode=None,
    hoversubplots=None,
    iciclecolorway=None,
    images=None,
    imagedefaults=None,
    legend=None,
    map=None,
    mapbox=None,
    margin=None,
    meta=None,
    metasrc=None,
    minreducedheight=None,
    minreducedwidth=None,
    modebar=None,
    newselection=None,
    newshape=None,
    paper_bgcolor=None,
    piecolorway=None,
    plot_bgcolor=None,
    polar=None,
    scattergap=None,
    scattermode=None,
    scene=None,
    selectdirection=None,
    selectionrevision=None,
    selections=None,
    selectiondefaults=None,
    separators=None,
    shapes=None,
    shapedefaults=None,
    showlegend=None,
    sliders=None,
    sliderdefaults=None,
    smith=None,
    spikedistance=None,
    sunburstcolorway=None,
    template=None,
    ternary=None,
    title=None,
    transition=None,
    treemapcolorway=None,
    uirevision=None,
    uniformtext=None,
    updatemenus=None,
    updatemenudefaults=None,
    violingap=None,
    violingroupgap=None,
    violinmode=None,
    waterfallgap=None,
    waterfallgroupgap=None,
    waterfallmode=None,
    width=None,
    xaxis=None,
    yaxis=None,
    **kwargs,
)
Docstring:
Base class for the layout type. The Layout class itself is a
code-generated subclass.
Init docstring:
Construct a new Layout object

Parameters
----------
arg
    dict of properties compatible with this constructor or
    an instance of :class:`plotly.graph_objs.Layout`
activeselection
    :class:`plotly.graph_objects.layout.Activeselection`
    instance or dict with compatible properties
activeshape
    :class:`plotly.graph_objects.layout.Activeshape`
    instance or dict with compatible properties
annotations
    A tuple of
    :class:`plotly.graph_objects.layout.Annotation`
    instances or dicts with compatible properties
annotationdefaults
    When used in a template (as
    layout.template.layout.annotationdefaults), sets the
    default property values to use for elements of
    layout.annotations
autosize
    Determines whether or not a layout width or height that
    has been left undefined by the user is initialized on
    each relayout. Note that, regardless of this attribute,
    an undefined layout width or height is always
    initialized on the first call to plot.
autotypenumbers
    Using "strict" a numeric string in trace data is not
    converted to a number. Using *convert types* a numeric
    string in trace data may be treated as a number during
    automatic axis `type` detection. This is the default
    value; however it could be overridden for individual
    axes.
barcornerradius
    Sets the rounding of bar corners. May be an integer
    number of pixels, or a percentage of bar width (as a
    string ending in %).
bargap
    Sets the gap (in plot fraction) between bars of
    adjacent location coordinates.
bargroupgap
    Sets the gap (in plot fraction) between bars of the
    same location coordinate.
barmode
    Determines how bars at the same location coordinate are
    displayed on the graph. With "stack", the bars are
    stacked on top of one another With "relative", the bars
    are stacked on top of one another, with negative values
    below the axis, positive values above With "group", the
    bars are plotted next to one another centered around
    the shared location. With "overlay", the bars are
    plotted over one another, you might need to reduce
    "opacity" to see multiple bars.
barnorm
    Sets the normalization for bar traces on the graph.
    With "fraction", the value of each bar is divided by
    the sum of all values at that location coordinate.
    "percent" is the same but multiplied by 100 to show
    percentages.
boxgap
    Sets the gap (in plot fraction) between boxes of
    adjacent location coordinates. Has no effect on traces
    that have "width" set.
boxgroupgap
    Sets the gap (in plot fraction) between boxes of the
    same location coordinate. Has no effect on traces that
    have "width" set.
boxmode
    Determines how boxes at the same location coordinate
    are displayed on the graph. If "group", the boxes are
    plotted next to one another centered around the shared
    location. If "overlay", the boxes are plotted over one
    another, you might need to set "opacity" to see them
    multiple boxes. Has no effect on traces that have
    "width" set.
calendar
    Sets the default calendar system to use for
    interpreting and displaying dates throughout the plot.
clickmode
    Determines the mode of single click interactions.
    "event" is the default value and emits the
    `plotly_click` event. In addition this mode emits the
    `plotly_selected` event in drag modes "lasso" and
    "select", but with no event data attached (kept for
    compatibility reasons). The "select" flag enables
    selecting single data points via click. This mode also
    supports persistent selections, meaning that pressing
    Shift while clicking, adds to / subtracts from an
    existing selection. "select" with `hovermode`: "x" can
    be confusing, consider explicitly setting `hovermode`:
    "closest" when using this feature. Selection events are
    sent accordingly as long as "event" flag is set as
    well. When the "event" flag is missing, `plotly_click`
    and `plotly_selected` events are not fired.
coloraxis
    :class:`plotly.graph_objects.layout.Coloraxis` instance
    or dict with compatible properties
colorscale
    :class:`plotly.graph_objects.layout.Colorscale`
    instance or dict with compatible properties
colorway
    Sets the default trace colors.
computed
    Placeholder for exporting automargin-impacting values
    namely `margin.t`, `margin.b`, `margin.l` and
    `margin.r` in "full-json" mode.
datarevision
    If provided, a changed value tells `Plotly.react` that
    one or more data arrays has changed. This way you can
    modify arrays in-place rather than making a complete
    new copy for an incremental change. If NOT provided,
    `Plotly.react` assumes that data arrays are being
    treated as immutable, thus any data array with a
    different identity from its predecessor contains new
    data.
dragmode
    Determines the mode of drag interactions. "select" and
    "lasso" apply only to scatter traces with markers or
    text. "orbit" and "turntable" apply only to 3D scenes.
editrevision
    Controls persistence of user-driven changes in
    `editable: true` configuration, other than trace names
    and axis titles. Defaults to `layout.uirevision`.
extendfunnelareacolors
    If `true`, the funnelarea slice colors (whether given
    by `funnelareacolorway` or inherited from `colorway`)
    will be extended to three times its original length by
    first repeating every color 20% lighter then each color
    20% darker. This is intended to reduce the likelihood
    of reusing the same color when you have many slices,
    but you can set `false` to disable. Colors provided in
    the trace, using `marker.colors`, are never extended.
extendiciclecolors
    If `true`, the icicle slice colors (whether given by
    `iciclecolorway` or inherited from `colorway`) will be
    extended to three times its original length by first
    repeating every color 20% lighter then each color 20%
    darker. This is intended to reduce the likelihood of
    reusing the same color when you have many slices, but
    you can set `false` to disable. Colors provided in the
    trace, using `marker.colors`, are never extended.
extendpiecolors
    If `true`, the pie slice colors (whether given by
    `piecolorway` or inherited from `colorway`) will be
    extended to three times its original length by first
    repeating every color 20% lighter then each color 20%
    darker. This is intended to reduce the likelihood of
    reusing the same color when you have many slices, but
    you can set `false` to disable. Colors provided in the
    trace, using `marker.colors`, are never extended.
extendsunburstcolors
    If `true`, the sunburst slice colors (whether given by
    `sunburstcolorway` or inherited from `colorway`) will
    be extended to three times its original length by first
    repeating every color 20% lighter then each color 20%
    darker. This is intended to reduce the likelihood of
    reusing the same color when you have many slices, but
    you can set `false` to disable. Colors provided in the
    trace, using `marker.colors`, are never extended.
extendtreemapcolors
    If `true`, the treemap slice colors (whether given by
    `treemapcolorway` or inherited from `colorway`) will be
    extended to three times its original length by first
    repeating every color 20% lighter then each color 20%
    darker. This is intended to reduce the likelihood of
    reusing the same color when you have many slices, but
    you can set `false` to disable. Colors provided in the
    trace, using `marker.colors`, are never extended.
font
    Sets the global font. Note that fonts used in traces
    and other layout components inherit from the global
    font.
funnelareacolorway
    Sets the default funnelarea slice colors. Defaults to
    the main `colorway` used for trace colors. If you
    specify a new list here it can still be extended with
    lighter and darker colors, see
    `extendfunnelareacolors`.
funnelgap
    Sets the gap (in plot fraction) between bars of
    adjacent location coordinates.
funnelgroupgap
    Sets the gap (in plot fraction) between bars of the
    same location coordinate.
funnelmode
    Determines how bars at the same location coordinate are
    displayed on the graph. With "stack", the bars are
    stacked on top of one another With "group", the bars
    are plotted next to one another centered around the
    shared location. With "overlay", the bars are plotted
    over one another, you might need to reduce "opacity" to
    see multiple bars.
geo
    :class:`plotly.graph_objects.layout.Geo` instance or
    dict with compatible properties
grid
    :class:`plotly.graph_objects.layout.Grid` instance or
    dict with compatible properties
height
    Sets the plot's height (in px).
hiddenlabels
    hiddenlabels is the funnelarea & pie chart analog of
    visible:'legendonly' but it can contain many labels,
    and can simultaneously hide slices from several
    pies/funnelarea charts
hiddenlabelssrc
    Sets the source reference on Chart Studio Cloud for
    `hiddenlabels`.
hidesources
    Determines whether or not a text link citing the data
    source is placed at the bottom-right cored of the
    figure. Has only an effect only on graphs that have
    been generated via forked graphs from the Chart Studio
    Cloud (at https://chart-studio.plotly.com or on-
    premise).
hoverdistance
    Sets the default distance (in pixels) to look for data
    to add hover labels (-1 means no cutoff, 0 means no
    looking for data). This is only a real distance for
    hovering on point-like objects, like scatter points.
    For area-like objects (bars, scatter fills, etc)
    hovering is on inside the area and off outside, but
    these objects will not supersede hover on point-like
    objects in case of conflict.
hoverlabel
    :class:`plotly.graph_objects.layout.Hoverlabel`
    instance or dict with compatible properties
hovermode
    Determines the mode of hover interactions. If
    "closest", a single hoverlabel will appear for the
    "closest" point within the `hoverdistance`. If "x" (or
    "y"), multiple hoverlabels will appear for multiple
    points at the "closest" x- (or y-) coordinate within
    the `hoverdistance`, with the caveat that no more than
    one hoverlabel will appear per trace. If *x unified*
    (or *y unified*), a single hoverlabel will appear
    multiple points at the closest x- (or y-) coordinate
    within the `hoverdistance` with the caveat that no more
    than one hoverlabel will appear per trace. In this
    mode, spikelines are enabled by default perpendicular
    to the specified axis. If false, hover interactions are
    disabled.
hoversubplots
    Determines expansion of hover effects to other subplots
    If "single" just the axis pair of the primary point is
    included without overlaying subplots. If "overlaying"
    all subplots using the main axis and occupying the same
    space are included. If "axis", also include stacked
    subplots using the same axis when `hovermode` is set to
    "x", *x unified*, "y" or *y unified*.
iciclecolorway
    Sets the default icicle slice colors. Defaults to the
    main `colorway` used for trace colors. If you specify a
    new list here it can still be extended with lighter and
    darker colors, see `extendiciclecolors`.
images
    A tuple of :class:`plotly.graph_objects.layout.Image`
    instances or dicts with compatible properties
imagedefaults
    When used in a template (as
    layout.template.layout.imagedefaults), sets the default
    property values to use for elements of layout.images
legend
    :class:`plotly.graph_objects.layout.Legend` instance or
    dict with compatible properties
map
    :class:`plotly.graph_objects.layout.Map` instance or
    dict with compatible properties
mapbox
    :class:`plotly.graph_objects.layout.Mapbox` instance or
    dict with compatible properties
margin
    :class:`plotly.graph_objects.layout.Margin` instance or
    dict with compatible properties
meta
    Assigns extra meta information that can be used in
    various `text` attributes. Attributes such as the
    graph, axis and colorbar `title.text`, annotation
    `text` `trace.name` in legend items, `rangeselector`,
    `updatemenus` and `sliders` `label` text all support
    `meta`. One can access `meta` fields using template
    strings: `%{meta[i]}` where `i` is the index of the
    `meta` item in question. `meta` can also be an object
    for example `{key: value}` which can be accessed
    %{meta[key]}.
metasrc
    Sets the source reference on Chart Studio Cloud for
    `meta`.
minreducedheight
    Minimum height of the plot with margin.automargin
    applied (in px)
minreducedwidth
    Minimum width of the plot with margin.automargin
    applied (in px)
modebar
    :class:`plotly.graph_objects.layout.Modebar` instance
    or dict with compatible properties
newselection
    :class:`plotly.graph_objects.layout.Newselection`
    instance or dict with compatible properties
newshape
    :class:`plotly.graph_objects.layout.Newshape` instance
    or dict with compatible properties
paper_bgcolor
    Sets the background color of the paper where the graph
    is drawn.
piecolorway
    Sets the default pie slice colors. Defaults to the main
    `colorway` used for trace colors. If you specify a new
    list here it can still be extended with lighter and
    darker colors, see `extendpiecolors`.
plot_bgcolor
    Sets the background color of the plotting area in-
    between x and y axes.
polar
    :class:`plotly.graph_objects.layout.Polar` instance or
    dict with compatible properties
scattergap
    Sets the gap (in plot fraction) between scatter points
    of adjacent location coordinates. Defaults to `bargap`.
scattermode
    Determines how scatter points at the same location
    coordinate are displayed on the graph. With "group",
    the scatter points are plotted next to one another
    centered around the shared location. With "overlay",
    the scatter points are plotted over one another, you
    might need to reduce "opacity" to see multiple scatter
    points.
scene
    :class:`plotly.graph_objects.layout.Scene` instance or
    dict with compatible properties
selectdirection
    When `dragmode` is set to "select", this limits the
    selection of the drag to horizontal, vertical or
    diagonal. "h" only allows horizontal selection, "v"
    only vertical, "d" only diagonal and "any" sets no
    limit.
selectionrevision
    Controls persistence of user-driven changes in selected
    points from all traces.
selections
    A tuple of
    :class:`plotly.graph_objects.layout.Selection`
    instances or dicts with compatible properties
selectiondefaults
    When used in a template (as
    layout.template.layout.selectiondefaults), sets the
    default property values to use for elements of
    layout.selections
separators
    Sets the decimal and thousand separators. For example,
    *. * puts a '.' before decimals and a space between
    thousands. In English locales, dflt is ".," but other
    locales may alter this default.
shapes
    A tuple of :class:`plotly.graph_objects.layout.Shape`
    instances or dicts with compatible properties
shapedefaults
    When used in a template (as
    layout.template.layout.shapedefaults), sets the default
    property values to use for elements of layout.shapes
showlegend
    Determines whether or not a legend is drawn. Default is
    `true` if there is a trace to show and any of these: a)
    Two or more traces would by default be shown in the
    legend. b) One pie trace is shown in the legend. c) One
    trace is explicitly given with `showlegend: true`.
sliders
    A tuple of :class:`plotly.graph_objects.layout.Slider`
    instances or dicts with compatible properties
sliderdefaults
    When used in a template (as
    layout.template.layout.sliderdefaults), sets the
    default property values to use for elements of
    layout.sliders
smith
    :class:`plotly.graph_objects.layout.Smith` instance or
    dict with compatible properties
spikedistance
    Sets the default distance (in pixels) to look for data
    to draw spikelines to (-1 means no cutoff, 0 means no
    looking for data). As with hoverdistance, distance does
    not apply to area-like objects. In addition, some
    objects can be hovered on but will not generate
    spikelines, such as scatter fills.
sunburstcolorway
    Sets the default sunburst slice colors. Defaults to the
    main `colorway` used for trace colors. If you specify a
    new list here it can still be extended with lighter and
    darker colors, see `extendsunburstcolors`.
template
    Default attributes to be applied to the plot. This
    should be a dict with format: `{'layout':
    layoutTemplate, 'data': {trace_type: [traceTemplate,
    ...], ...}}` where `layoutTemplate` is a dict matching
    the structure of `figure.layout` and `traceTemplate` is
    a dict matching the structure of the trace with type
    `trace_type` (e.g. 'scatter'). Alternatively, this may
    be specified as an instance of
    plotly.graph_objs.layout.Template.  Trace templates are
    applied cyclically to traces of each type. Container
    arrays (eg `annotations`) have special handling: An
    object ending in `defaults` (eg `annotationdefaults`)
    is applied to each array item. But if an item has a
    `templateitemname` key we look in the template array
    for an item with matching `name` and apply that
    instead. If no matching `name` is found we mark the
    item invisible. Any named template item not referenced
    is appended to the end of the array, so this can be

In [20]:
pd.DataFrame([[7.0, 0.27, 0.36, 20.7, 0.045, 45.0, 170.0, 1.001, 3.0, 0.45, 8.8], [7.0, 0.27, 0.36, 20.7, 0.045, 45.0, 170.0, 1.001, 3.0, 0.45, 8.8]])

    0     1     2     3      4     5      6      7    8     9    10
0  7.0  0.27  0.36  20.7  0.045  45.0  170.0  1.001  3.0  0.45  8.8
1  7.0  0.27  0.36  20.7  0.045  45.0  170.0  1.001  3.0  0.45  8.8

In [22]:
input = {
  "input": [[7.0, 0.27, 0.36, 20.7, 0.045, 45.0, 170.0, 1.001, 3.0, 0.45, 8.8], [7.0, 0.27, 0.36, 20.7, 0.045, 45.0, 170.0, 1.001, 3.0, 0.45, 8.8]]
}
pd.DataFrame(input["input"])

    0     1     2     3      4     5      6      7    8     9    10
0  7.0  0.27  0.36  20.7  0.045  45.0  170.0  1.001  3.0  0.45  8.8
1  7.0  0.27  0.36  20.7  0.045  45.0  170.0  1.001  3.0  0.45  8.8